### ISSUE TITLE
Tightly couple with yesql

### ISSUE THREAD

**Issue by pupeno** [luminus-framework/conman#2]
It feels that the current library is too tightly couple with yesql and that will limit it and its adoption. I propose we at least start by having a very clear statement that this library is intended to be used with any other DSL and that we welcome pull requests of other integrations.

I think as a second step we should try to decouple yesql from the library while still keeping an easy integration. One of the issues we'll encounter here is dependencies. People using one DSL won't want to include all others, so I think we should have a base library, conman and then conman-yesql, conman-honeysql and so on that depend on conman and provide the higher level abstractions/integrations.

What do you think?

I just don't want someone to look at this, think "Oh, this is a good idea, I'll make another one for my own DSL" when they could just extend this one.

**Comment by yogthos** [comment]
I think the primary function of the library is working around yesql to be honest. Since yesql generates functions from sql files there's a need to massage them to work within the context of luminus.

The `clj-dbcp` connection pooling library is easy enough to use otherwise. For example, honey sql is completely connection agnostic so you'd be writing the wrappers by hand and use the connection there.

It might be interesting to write a library that generates wrappers for honey sql the way yesql does, but I don't think that should be a goal for this library.

Also, from maintenance perspective the more backends you start supporting the more work it is to keep things running. I find this already to be a bit of a burden with Luminus, so I'm leaning towards picking one stack and making it work well than supporting a lot of different ways to do things.
